import type { ArtTestItem } from "./types"

/** The original fifty AI Art Turing Test items in Google Form order. */
export const artTestItems: ArtTestItem[] = [
  {
    id: 1,
    title: "Angel Woman",
    trueLabel: "human",
    imagePath: "/art/0.jpg",
    width: 740,
    height: 527,
    attribution: "This is “Living Saint Hazel” by LJ Koh, as seen at /r/ImaginaryWarhammer.",
    attributionUrl:
      "https://www.reddit.com/r/ImaginaryWarhammer/comments/jk5hc7/living_saint_hazel_custom_commission_by_l_j_koh/",
    commentary:
      "This was the picture that sparked the strongest disagreement, measured by the sum of people who said it was the most-certainly-human picture in the dataset plus the people who said it was the most-certainly-AI picture. Some of the people who got it right commented that it was from Warhammer and the uniforms had accurate Warhammer symbols - if I had realized this, I would have disqualified it, sorry.",
    originalUrl:
      "https://lh6.googleusercontent.com/4JVsmfzpQqhaDFtmN_omx9GKb8MrZ6FtARpmNkCsgE8OKfyLdBGv3sXaVqPlTzRic9oV_LXYK4GLxS2_fX9qIMzbYrqaIcQ2zGuwBBCaKQTXCV2rrjPicfd1Z-PnKey2Ig=w740",
  },
  {
    id: 2,
    title: "Saint In Mountains",
    trueLabel: "human",
    imagePath: "/art/1.png",
    width: 540,
    height: 815,
    attribution:
      "This is “St. Anthony Abbot Tempted By A Heap Of Gold”, by the “Ozzervanza Master”, an unknown Italian Renaissance painter from around 1435.",
    attributionUrl: "https://en.wikipedia.org/wiki/Saint_Anthony_Abbot_Tempted_by_a_Heap_of_Gold",
    commentary:
      "Apparently it used to have a heap of gold in the bottom corner tempting St. Anthony, but this was “scraped out”. If I had known that originally, I would have disqualified this one too, since it might spoil something uniquely human about the integrity of the composition.",
    originalUrl:
      "https://lh5.googleusercontent.com/WMY-CSQ8PkQP3WQkxW3ihdhjHMdqesm0fvFj8_Wdd7Xx3x-ga0VH4c5f0z6URKnth5Zi6v1GjU1OmC-ttu-N6w7eT2mhMxL8CZ82FJrtAgEHOOQiRiaBdj6QoS7WnLzV3w=w540",
  },
  {
    id: 3,
    title: "Blue Hair Anime Girl",
    trueLabel: "human",
    imagePath: "/art/2.jpg",
    width: 740,
    height: 562,
    attribution: "This is Hatsune Miku, a “virtual idol” from the late 2000s/early 2010s.",
    attributionUrl: "https://www.zerochan.net/3532501",
    originalUrl:
      "https://lh6.googleusercontent.com/2b-8iGfBqE1x5gPoZolo0dlKKIMvaCR_tprxvK_w04VT2_EO30itejrr6-2Sv6Dt7dH3Srqudhmeabxj9mxlqJlgeOAFidWPQS_WVhbNzUcGDUeQpL-OTxw9co7NNqLL4g=w740",
  },
  {
    id: 4,
    title: "Girl In Field",
    trueLabel: "ai",
    imagePath: "/art/3.png",
    width: 740,
    height: 463,
    attribution:
      "This image was generated by Ryan Wise, an AI art hobbyist who reads ACX and responded to my request for good AI pictures.",
    originalUrl:
      "https://lh5.googleusercontent.com/C6iVp4WxtM1W2KT9XRyjoqsUMVQ-Hsf8efGdO2N-BaO9Z0n3ujITA2oxXpcks9GRM03_F_nanKRoFfsZY0Fb6Os2WP1XidxCe6eocirnOgLAXFnO4LvV2IPbQ3x6Iea_RQ=w740",
  },
  {
    id: 5,
    title: "Double Starship",
    trueLabel: "human",
    imagePath: "/art/4.png",
    width: 740,
    height: 964,
    attribution: "This is “Malabar”, by Wojtek Kapusta.",
    attributionUrl:
      "https://www.reddit.com/r/ImaginaryStarships/comments/1g21h7e/malabar_by_wojtek_kapusta/",
    originalUrl:
      "https://lh5.googleusercontent.com/SghFEzcoCjKUhoc-S_4se4ByIB9b4Pq_nhmNfFEvnGaAmIKWcZkfFact6WJbdzzTbco_2dxu00F5VDn-Wl2ch9v9UwQf0MtFyGvizK_o1NofAZX_IkEfC8LVUI-xV7G1uw=w740",
  },
  {
    id: 6,
    title: "Bright Jumble Woman",
    trueLabel: "ai",
    imagePath: "/art/5.png",
    width: 740,
    height: 509,
    attribution: "This is AI art by Ryan Wise.",
    originalUrl:
      "https://lh4.googleusercontent.com/GCYGLnpvVZiXPwkEmJOkRIg7YWn0JfAAL84Om-7yNWs7RXs8_nQS_Y_-e1hzqEynnKR_C_OOfhNBbu9m3mOBnY082IqN9o2UHAQhk9L11n6rwI7KR8811OolifUYGjz7fQ=w740",
  },
  {
    id: 7,
    title: "Cherub",
    trueLabel: "ai",
    imagePath: "/art/6.jpg",
    width: 740,
    height: 557,
    attribution: "This one was generated by another ACX reader, Jack Galler.",
    attributionUrl: "https://x.com/gallerdude",
    originalUrl:
      "https://lh6.googleusercontent.com/0HbACcQ0486gHsz9XaS3Z-IEdQS-iUJjzZ52BuM-npu3tuU-s2aIGby0C8ZSdTRECHNKV43KBvtIz73Du7v5hc7JjS8J8loPF0aP9YRAtgY7j2Fgwf5oP1DNBEQJ7KhJIA=w740",
  },
  {
    id: 8,
    title: "Praying In Garden",
    trueLabel: "human",
    imagePath: "/art/7.png",
    width: 698,
    height: 503,
    attribution: "This is “Agony In The Garden” by Andrea Mantenga, 1455.",
    attributionUrl: "https://en.wikipedia.org/wiki/Agony_in_the_Garden_(Mantegna,_London)",
    originalUrl:
      "https://lh5.googleusercontent.com/hh3qFWrViDThbyOqbt3IxIghlkhyfkStmXKPcI-AsC43hs5mvDMcvpAcSIeZZT8Avgp_Zo5kkqyAJIo__8MaJ0gNy1-9hX2NnpR2XIhj6R8_phFnMojcabpRmVTmnQ8N-A=w698",
  },
  {
    id: 9,
    title: "Tropical Garden",
    trueLabel: "human",
    imagePath: "/art/8.png",
    width: 644,
    height: 427,
    attribution: "This is “Garden” by David Hockney.",
    attributionUrl: "https://www.artsy.net/artwork/david-hockney-garden-2018",
    commentary: "A very similar Hockney painting sold for $8 million in 2021.",
    originalUrl:
      "https://lh6.googleusercontent.com/_pSYzKd7T1Mv3JGQv10MRsjVM6KlbxEx3SVXs0E0Lzxof0rf9huxcy1VshEXcTbvtvgX8KpNF6IOqPfq3X1dSDGUI74gD3UQgVZ_4gX7lhvRAZTV_EfTA-d6bPGu2nKDmw=w644",
  },
  {
    id: 10,
    title: "Ancient Gate",
    trueLabel: "ai",
    imagePath: "/art/9.jpg",
    width: 740,
    height: 925,
    attribution:
      "This is by Piotr Binkowski, a well-known AI art maker who posts his work on his Twitter.",
    attributionUrl: "https://x.com/piotrbinkowski",
    originalUrl:
      "https://lh6.googleusercontent.com/HzT_04PhPvCgyxwjVo_1yrrxfJw79_2GU-pBsmrloHGA-Op-WMhpMFm-8UxSuPRujdeMkq0csw9obGpf5yguvcME9hHmqPFgtuV27H7LV9c82io__09BrQC-wOTmmVVeiw=w740",
  },
  {
    id: 11,
    title: "Green Hills",
    trueLabel: "ai",
    imagePath: "/art/10.png",
    width: 740,
    height: 707,
    attribution: "This is AI art by Jack Galler.",
    attributionUrl: "https://x.com/gallerdude",
    originalUrl:
      "https://lh4.googleusercontent.com/zRIZw2PbXCiIInuCA2N9lULyAxEBH6tnGyEBekJ7zsnPin7k4VTfbBULgfeiCMXg9pgYHK7MgHqL6ngEEYG4bVAg4AmyOMs_JYh40pyNfLPMVKD3rsDcSjgQC1FV5zB7Jg=w740",
  },
  {
    id: 12,
    title: "Bucolic Scene",
    trueLabel: "human",
    imagePath: "/art/11.png",
    width: 740,
    height: 519,
    attribution:
      "This is “Dover Plains” by Asher Durand, painted 1848. It depicts the Hudson Valley in New York.",
    attributionUrl: "https://americanart.si.edu/artwork/dover-plains-dutchess-county-new-york-7642",
    originalUrl:
      "https://lh3.googleusercontent.com/xxi5nItar_N433HC1X54UxJ3ZftmHcyQn7QXJAAXMRk-STH2s59YU9gp-hIrRSnlrIvop2TnJ-uw6WAuwme-QgF0L5r12mkA6qPs27FfHD-5I64VhgMKr8dgjiw0Yycc2A=w740",
  },
  {
    id: 13,
    title: "Anime Girl In Black",
    trueLabel: "ai",
    imagePath: "/art/12.png",
    width: 740,
    height: 951,
    attribution:
      "This is AI art. Sorry, I seem to have lost the original source on this one, let me know if it’s yours.",
    originalUrl:
      "https://lh3.googleusercontent.com/FWGJ60hx5y2aWfQf1IjBUJEhPaYkGGJUdmZHdCAnPazSYLwYt2emo_aQhMLD2aUlIVRO81LDjUUg6R-QKSXCNMurPP4G10EQLrfhoMXTdfx16c8YIhKfg64EvK-3KbgVfw=w740",
  },
  {
    id: 14,
    title: "Fancy Car",
    trueLabel: "human",
    imagePath: "/art/13.jpg",
    width: 740,
    height: 416,
    attribution: "This is “Ferrari Testarossa Neon Retrowave Synth”, by Arslan Safiullin.",
    attributionUrl:
      "https://www.goodfon.com/rendering/wallpaper-ferrari-testarossa-ferrari-testarossa-neon-retrowave-synth-r.html",
    originalUrl:
      "https://lh4.googleusercontent.com/R1qIKlWCWgWmD9tSTqku4zv_bDAA8PzZEjyu6tJfPQ_YRS5rtgBFSzmLYPzk07bQtkq4m36ydiYaZw6RsPmA5Jl_yDpsNsc97mFiRNxndJn44Ywqjrnqnmb1GTV2so-wvw=w740",
  },
  {
    id: 15,
    title: "Greek Temple",
    trueLabel: "human",
    imagePath: "/art/14.jpg",
    width: 710,
    height: 525,
    attribution: "This is “The Apotheosis Of Homer”, by Jean-Auguste-Dominique Ingres (1827).",
    attributionUrl: "https://en.wikipedia.org/wiki/The_Apotheosis_of_Homer_(Ingres)",
    commentary:
      "It's the only one that was (sort of) a trick question: after I selected it for the dataset, I noticed it contained text. Normally that would be disqualifying (correct text is too obviously human). But the most prominent text is the “OMHP” on the temple, which spells “Homer” in Greek but is gibberish in English. I was curious how many people would judge a famous work of art to be AI-generated just because it had seemingly gibberish text on it; the answer was 60%.",
    originalUrl:
      "https://lh6.googleusercontent.com/FnkkKeLpcM3Hz0_e3StxjD3yfagzYnXSZ8AimSPqjulJwTRZQa3pUVrtQ4a9qEvWu8SMlApmzJsOVEr2LBPzLgRnx7VUYG7PPfiJvNTKeV1EWoByJp6DwFUw3_Ppqppesw=w710",
  },
  {
    id: 16,
    title: "String Doll",
    trueLabel: "ai",
    imagePath: "/art/15.png",
    width: 740,
    height: 951,
    attribution: "This is “Strings Come Alive” by Nikko P at Nightcafe.",
    attributionUrl: "https://creator.nightcafe.studio/creation/GyesAtcTkByeTnntC0Ej",
    commentary: "This was the picture that people were most confident was AI (they were right).",
    originalUrl:
      "https://lh5.googleusercontent.com/SmH6W22Iqb5vlVLP-x--dkhES2lyOzT1g_lTB-WbCYFZICJtBHHWFXydcAaplwSx_CY8LPYcz38_5TSfA5p9N2DjfLKenEuZieIqfIkFgdf9A-_H_zM1Yc2siLCZeNVNUA=w740",
  },
  {
    id: 17,
    title: "Angry Crosses",
    trueLabel: "ai",
    imagePath: "/art/16.png",
    width: 740,
    height: 509,
    attribution: "This is AI art by Ryan Wise.",
    originalUrl:
      "https://lh6.googleusercontent.com/HmAoh4tVxaqtiexz0G47JPV9ksjgqeNuomTKB9kxELcHs3E2TXS4KdVuH6XID_AQTXUiLxpmzwJ-F4YVrFSIPDhX3ZeymP9FX2g6H4gGy_wBkb91RME_CwtvsyJwnsh6mg=w740",
  },
  {
    id: 18,
    title: "Rainbow Girl",
    trueLabel: "human",
    imagePath: "/art/17.png",
    width: 577,
    height: 626,
    attribution: "This is “Rainbow Hair” by rjv-ilustracion.",
    attributionUrl: "https://www.deviantart.com/rjv-ilustracion/art/Rainbow-hair-934739043",
    originalUrl:
      "https://lh4.googleusercontent.com/wexmwYEBsj459XDNp07AdC13OB8szydq36ZSD-ik8uJNkbNJm09lkJZRsdgi6Np3e4uCHK_z_qpdhCHPpLOv4fCytUy729NwIANrXOxYsTmQ8BffnSxGiibAFurbuGl0ew=w577",
  },
  {
    id: 19,
    title: "Creepy Skull",
    trueLabel: "human",
    imagePath: "/art/18.jpg",
    width: 740,
    height: 493,
    attribution:
      "This is “Untitled (Skull)” by Jean-Michael Basquiat in 1981. A version of this painting sold for $110 million in 2017 and was “the priciest work ever sold by a US artist”.",
    originalUrl:
      "https://lh6.googleusercontent.com/mErjKkxsv2enDfoS75Zb5ePx0gpkU4dnU8ZzNlmZ3_MMCKLKO31PXy5nYfKHZpI7jH8yn8e-qexM6f88N64DkkxYMDUaIeZVZtu2N-23nItUUVUIC7NvoCqs0rFiPgR_jw=w740",
  },
  {
    id: 20,
    title: "Leafy Lane",
    trueLabel: "ai",
    imagePath: "/art/19.png",
    width: 740,
    height: 707,
    attribution: "This is AI art by Jack Galler.",
    attributionUrl: "https://x.com/gallerdude",
    originalUrl:
      "https://lh4.googleusercontent.com/C2aBGRzokTR47vVexXy39Up67CSkzMilm5XDnV5FJe0nhW8NdrfDOBpRzq85-n2QXW110fQ5dR7x9JyGqqcnbQFHHrW4AnFgBxP3U12Enna4Ybcrc3ZHdUT7FdyxpsubeA=w740",
  },
  {
    id: 21,
    title: "Ice Princess",
    trueLabel: "ai",
    imagePath: "/art/20.png",
    width: 512,
    height: 768,
    attribution: "This is “Snow Princess” by Ai Xi, seen at PixAI.",
    attributionUrl: "https://pixai.art/artwork/1711590348726222704?lang=de",
    originalUrl:
      "https://lh4.googleusercontent.com/Mmxyml1MQKTeKjMOTukg041f2Kve2jSCmHGx41FKprtsrlniyDdcfXWlVjmo9os_paYRbJ8u4FqcuZvNaiVtcCRUv_Sk_9UGE2jPL2ByZFXuxBbdepMxcvBNyCP3YPlX7A=w512",
  },
  {
    id: 22,
    title: "Celestial Display",
    trueLabel: "human",
    imagePath: "/art/21.png",
    width: 740,
    height: 517,
    attribution: "This is “Five Minutes Of Silence” by Hangmoon, seen at DeviantArt.",
    attributionUrl: "https://www.deviantart.com/hangmoon/art/Five-minutes-of-silence-676043151",
    commentary: "This was the top-rated human picture.",
    originalUrl:
      "https://lh4.googleusercontent.com/TyuIMyLU2Z5WOFjzp11pokQbTiggc-vHqRgW7JganKRMWjFsXdV_oh_MR4KHVqCyw4ALwfvaMJRO8WSv91FENWtEOJQmaEJgRG2ezDM1WD3V0xlJMp-9KZyjUGq0dPC_lQ=w740",
  },
  {
    id: 23,
    title: "Mother And Child",
    trueLabel: "ai",
    imagePath: "/art/22.png",
    width: 574,
    height: 1024,
    attribution: "This is “Ukrainian Madonna”, generated by TheLibertarianCatholic.",
    attributionUrl:
      "https://thelibertariancatholic.com/ai-creation-of-art-nouveau-mary-queen-of-heaven/",
    originalUrl:
      "https://lh6.googleusercontent.com/bhq-7O87krFgrRUEvVJpSob1NCyWd3mpE7iZpWZisZgO4rviSQcGE3yjMvDIMlLwQdm9VWc3oJJwNx0AZoq-9csiK78CvJ2g-7CjFjMaQfALnGtdclPNphfUpza6rCfhuw=w574",
  },
  {
    id: 24,
    title: "Fractured Lady",
    trueLabel: "ai",
    imagePath: "/art/23.png",
    width: 740,
    height: 509,
    attribution: "This is AI art by Ryan Wise.",
    originalUrl:
      "https://lh5.googleusercontent.com/FmqSHypc23-CIHv2MuHFsokJ_TkQOLMkrXAy8iAGuDKUZr2mExvZ8ywqmFVkE0hNWHGytCl8NcLc9C-KH1XDtahaeJxh_cCejnmb0aSNRAXjqnrcG2rtSuHb-7c118xtqw=w740",
  },
  {
    id: 25,
    title: "Giant Ship",
    trueLabel: "human",
    imagePath: "/art/24.png",
    width: 740,
    height: 565,
    attribution: "This is Victorian Megaship by Mitchell Stuart.",
    attributionUrl: "https://www.artstation.com/artwork/mzVo49",
    commentary:
      "This was the human picture that people got most wrong (i.e., were most likely to vote as AI).",
    originalUrl:
      "https://lh5.googleusercontent.com/lytjC9wx2eSpsR7-v65R0MJpAVAO7f50MjiuPeVxbjloz5IZ_ZonIxzL6f2680VqXBG6tix-MCU0YHWRLhHUwLSC0JJY3v7rKGV_DYCfY_nf6JBxJ663daV3E4ab9DTsTA=w740",
  },
  {
    id: 26,
    title: "Muscular Man",
    trueLabel: "ai",
    imagePath: "/art/25.png",
    width: 740,
    height: 509,
    attribution: "This is AI art by Ryan Wise.",
    originalUrl:
      "https://lh3.googleusercontent.com/jfHKVAwOwGKJVtPUnkqLLLD4y9lvFr-y3rg1MMRb8DfQnpGaiTcJLX-g64OI33Dz_kzqe2I4zVfxWPhMomDeGF8dN2abPB6fOvD_LFuyyGVb27mmHujN1SVWaXrbiObgig=w740",
  },
  {
    id: 27,
    title: "Minaret Boat",
    trueLabel: "ai",
    imagePath: "/art/26.png",
    width: 740,
    height: 740,
    attribution: "This is “Built For The Princess” by Nikko P at Nightcafe.",
    attributionUrl: "https://creator.nightcafe.studio/creation/9etGANoy57iZml5jEjmv",
    originalUrl:
      "https://lh5.googleusercontent.com/fym4irvU7YWCYXpwDg6ZxXinoTePYQzZRVl4Ln__o6f2QgEKRH2rsrIaDZkQkOLaDJUBYKDSEFizGNQ9SFGK-jaa-lNAj5KolFL1B368CL11Rk1B-ibNcgP6qTcT-mfLNw=w740",
  },
  {
    id: 28,
    title: "Purple Squares",
    trueLabel: "human",
    imagePath: "/art/27.png",
    width: 740,
    height: 574,
    attribution:
      "This is “Fire At Full Moon” by Paul Klee, and is supposed to be a “Cubist style depiction of a night sky”.",
    attributionUrl:
      "https://www.kingandmcgaw.com/prints/paul-klee/fire-at-full-moon-1933-427760#427760::border:50_frame:880229_glass:770007_media:1_mount:108644_mount-width:50_size:620,496",
    originalUrl:
      "https://lh6.googleusercontent.com/T4kx1Nf5Xg-vprRQmg-HYj_UoObGCSdkTUx1gjm0X0eimeOEkVNbByRCBbCIGW7LK_7TPdhEN4wuPtB3JwoLxR2reymmIzu4MSsx8K-M5exP7DPccO2hcBbBn1LSik713A=w740",
  },
  {
    id: 29,
    title: "People Sitting",
    trueLabel: "human",
    imagePath: "/art/28.jpg",
    width: 740,
    height: 577,
    attribution: "This is “Tailor’s Workshop” by Quiringh van Brekelenkam, 1660.",
    attributionUrl: "https://www.mbam.qc.ca/en/works/62729/",
    originalUrl:
      "https://lh5.googleusercontent.com/liJzgZgPB28m5_eJOXAQB-f7nrkBRKAjccOHmdpG65AXSfdxZRCoXyzgEbg-ATRenc56lNdo61MtVc8bQrFsGButGhHTdlR23kihf92Y7ONGGvfjgzPtoWLWKrlmfgutjg=w740",
  },
  {
    id: 30,
    title: "Girl In White",
    trueLabel: "human",
    imagePath: "/art/29.png",
    width: 740,
    height: 598,
    attribution: "This is “Portrait of Charlotte du Val d'Ognes” by Marie-Denise Villers (1801).",
    attributionUrl: "https://en.wikipedia.org/wiki/Portrait_of_Charlotte_du_Val_d%27Ognes",
    originalUrl:
      "https://lh6.googleusercontent.com/aioJmwtNB87RO8KHikGPZH2krgR6vxE2wO3O06siFZXH3r6hD8dDndsZl5ty2DIRHOrBbt-LjwReWFcTL-70Uk6bEtqA7M58VcEuZz7nEEZyYopkmvcVe3iih2h4X2iF5w=w740",
  },
  {
    id: 31,
    title: "Riverside Cafe",
    trueLabel: "ai",
    imagePath: "/art/30.png",
    width: 740,
    height: 934,
    attribution: "This is AI art by Jack Galler.",
    attributionUrl: "https://x.com/gallerdude",
    commentary: "This was the most popular picture in the dataset.",
    originalUrl:
      "https://lh3.googleusercontent.com/ElNSk7aqHo1o_0WuOF4SP3Fqh7vYvSErTMhMzS-NllBp0dzY0qR683fHU2nyPBAnYd6LbFB2mLgoeIYRITNBVJOM0azou-h990OMD2TemWa5avRkb4c0cXRtuFAzqkxxNg=w740",
  },
  {
    id: 32,
    title: "Serene River",
    trueLabel: "human",
    imagePath: "/art/31.png",
    width: 740,
    height: 464,
    attribution: "This is “Banks Of The Oise At Auvers”, by Charles-François Daubigny (1863)",
    attributionUrl: "https://www.slam.org/collection/objects/49181/",
    originalUrl:
      "https://lh3.googleusercontent.com/YGDMXJVvQIaOIHiG4K9z59RvbA-kZ2NzzjsKX6JIyjoyx5rtwx7EuNahWHvvFtyiNXGcUBxc7TUW7DhydqpkVZuaLnesAXOHzLrnOdCFdF9ZcVujqD-zI6Wn9hKJsG0xZw=w740",
  },
  {
    id: 33,
    title: "Turtle House",
    trueLabel: "ai",
    imagePath: "/art/32.png",
    width: 740,
    height: 601,
    attribution: "This is “Mobile Home”, by Bellemia, seen on Nightcafe.",
    attributionUrl: "https://creator.nightcafe.studio/creation/8tovejem47HTeDv44dTJ",
    originalUrl:
      "https://lh4.googleusercontent.com/VUrPWg_VNvpwbemlqswOhtkrGjUsZe4kxQUsPFCf72j-Naapc6HxhfubBC1HIKuE85Gy0x0lzGFp46ZgEFcL4Stwed-P7I889LbLLh7p_0lJkq5TNddsc2rnOXpFjQU4RQ=w740",
  },
  {
    id: 34,
    title: "Still Life",
    trueLabel: "ai",
    imagePath: "/art/33.jpg",
    width: 740,
    height: 1432,
    attribution: "This is AI art by Jack Galler.",
    attributionUrl: "https://x.com/gallerdude",
    originalUrl:
      "https://lh5.googleusercontent.com/mrfEsEKAPSPmPU_Hsj6SLzNMFgVHUvsTENLOKd_FNa_iG5liw1zQkAtaSmTbBpC2qH_m69xj0l4TuNpJf8RPf0UjLlQ5vG4fNqeQ_9XB_NWDQMHgztQUtZlj6c8SI_wMQA=w740",
  },
  {
    id: 35,
    title: "Wounded Christ",
    trueLabel: "human",
    imagePath: "/art/34.jpg",
    width: 740,
    height: 446,
    attribution: "This is “The Mourning Of Christ” by Giovanni Girolamo Savoldo (1515).",
    attributionUrl: "https://en.wikipedia.org/wiki/Giovanni_Girolamo_Savoldo",
    commentary:
      "This was the picture that people were most confident was human (they were right), but a few people protested and said that the anatomy was so wrong that it must be AI-generated. Sorry, I guess Giovanni Girolamo Savoldo just wasn’t very good at anatomy. Maybe that’s why Michelangelo had to dissect all those corpses.",
    originalUrl:
      "https://lh6.googleusercontent.com/FqVZ9uL_nyxEc9i7pv6T71KsYR1OsFg-xH9c6q7vsuEw50YHvVoqe9uuvxQhgR1P14bXM_Fxspx-lD_kG8X2G6NABNihaW19FjOM8LF8kdd6vQluWRn2Bz_CZfRmMI2A_g=w740",
  },
  {
    id: 36,
    title: "White Blob",
    trueLabel: "human",
    imagePath: "/art/35.jpg",
    width: 740,
    height: 528,
    attribution: "This is from “Le Lezard aux Plumes d'Or” by Joan Miro (1971).",
    attributionUrl: "https://www.nationalgalleries.org/art-and-artists/113686",
    originalUrl:
      "https://lh3.googleusercontent.com/p9Vvf7PIFjxsuvGuV2dYffIUY_U4ddNSaPXjnO8rPsElufNyAInVjbyC5iTZdc4UT8zNpZaghP_L-N3U2I9WAKTDIWkVC0MGqrc-nar3Fpvr9HonjejmvmrEf9D84UKBMA=w740",
  },
  {
    id: 37,
    title: "Weird Bird",
    trueLabel: "ai",
    imagePath: "/art/36.png",
    width: 740,
    height: 547,
    attribution: "This is AI art by Ryan Wise.",
    commentary:
      "People say AI can’t invent new styles, but I’ve never seen any human make this exact type of weird bird.",
    originalUrl:
      "https://lh4.googleusercontent.com/pcJLBMYHXzabsIeQ4zJSJQWnTsXuA4JiZgEZ2WCg9jKlk1Y4H6qPxOCRcEImn0UDo_bP3bOCyC-bxOrpA6_YlLi5Nw2MnCZmWcPIDdaAIxdctVgIRWAeViffcqjobqduOA=w740",
  },
  {
    id: 38,
    title: "Ominous Ruin",
    trueLabel: "ai",
    imagePath: "/art/37.png",
    width: 740,
    height: 458,
    attribution: "This is AI art by Ryan Wise.",
    originalUrl:
      "https://lh3.googleusercontent.com/271D5Q392mZBOPjf1cFMSb9uP1HNhcwoci-XelRsLTkW3e4We0Aw9lM6BJSh8qVYVw7A_KU8CgHITkfUF13dyLj9xfE0s3BxbjMB2-krdIyn07hAY7KxnKgdE5xOqgbTVg=w740",
  },
  {
    id: 39,
    title: "Vague Figures",
    trueLabel: "human",
    imagePath: "/art/38.png",
    width: 740,
    height: 468,
    attribution: "This is “Blood Thicker Than Mud”, by Cecily Brown (2021).",
    attributionUrl: "http://cecilybrown.com/untitled-blood-thicker-than-mud/",
    originalUrl:
      "https://lh4.googleusercontent.com/m9AgW4EC_ScSXAq64d8m_40XPCUBqUcH4gEnXWbQOUjPYsDo__xfgHXbTw3rx1Or6okQcgozccPPeCgqmu-ZMOh78fEUcpWjMhCI9HxaQMVVAz2VwB2BD7qV0R3PvnCSJQ=w740",
  },
  {
    id: 40,
    title: "Dragon Lady",
    trueLabel: "ai",
    imagePath: "/art/39.png",
    width: 740,
    height: 740,
    attribution: "This is “To Me, You’re Perfect” by Ria Hagane on Nightcafe, made with DALL-E3.",
    attributionUrl: "https://creator.nightcafe.studio/creation/XY6uAJuIoOUTIMlQxOza",
    originalUrl:
      "https://lh4.googleusercontent.com/LvIK-x_9nNlvVEKgqBSCscm0sC33A3viwSBnbAnkKvtTvhHakTYxWVF34JZjU0PnnEGNAP5MWkNXStYfsXiz1pTCiJb920RfvbF7UZPCC-GVg-ppk50zIAGLOLuYAw_AfA=w740",
  },
  {
    id: 41,
    title: "White Flag",
    trueLabel: "human",
    imagePath: "/art/40.png",
    width: 688,
    height: 999,
    attribution:
      "This is “Meeting At Krizky” by Alphonse Mucha (1916). It is part of his Slav Epic, a series of paintings on the history of Eastern Europe, and depicts a meeting of the Hussite sect, whose attempts to found a sort of proto-Protestantism would spark the 15th-century Hussite Wars.",
    attributionUrl: "https://www.muchafoundation.org/en/gallery/themes/theme/slav-epic/object/221",
    originalUrl:
      "https://lh5.googleusercontent.com/FqRJpFpDIAf_8Bd86EEkQoabeSy_B9-yxhlx4dzDlqRrVK_igmiOxo_AMgvxautcnryY5g1dUlbyTLMz1S4wmkDa6Yr9LZygcspXWn_cOmqpVy2ZaR-Z3tCSfQQ0Y-pplw=w688",
  },
  {
    id: 42,
    title: "Woman Unicorn",
    trueLabel: "human",
    imagePath: "/art/41.jpg",
    width: 740,
    height: 612,
    attribution: "This is “The Maiden And The Unicorn” by Domenichino (1602)",
    attributionUrl: "https://www.wga.hu/html_m/d/domenich/3/farnese.html",
    originalUrl:
      "https://lh6.googleusercontent.com/YRFzN8cTbjLhF7B1gEASeVbN048ofNwMsK3S2V9Dm14cNtvglE-U_6K3aSSk0oJFgF6uqgIab9Cm5LmP4wDC-kJN9raE3mKNso7_Ox00nEHGVMh1nSQnZ0H_rV61_bAQ6w=w740",
  },
  {
    id: 43,
    title: "Rooftops",
    trueLabel: "ai",
    imagePath: "/art/42.png",
    width: 512,
    height: 768,
    attribution:
      "This is AI art. I managed to lose this one, sorry! If it’s yours, let me know and I’ll give you credit.",
    originalUrl:
      "https://lh3.googleusercontent.com/7y99VuWSq-4JjEWXwqjKz7pSOeBWkdwsRHr7rbieqhT-61Yc4UzcBAYm_YWiAbptxbLtduoFjceI4lKz_csqk7sxVmZ9iZainv8XOPUMy_7MnK536fYOalkCkiGm1rTbow=w512",
  },
  {
    id: 44,
    title: "Paris Scene",
    trueLabel: "ai",
    imagePath: "/art/43.jpg",
    width: 740,
    height: 612,
    attribution: "This is AI art by Jack Galler.",
    attributionUrl: "https://x.com/gallerdude",
    commentary:
      "This was the AI picture that people got most wrong (i.e., were most likely to vote as human).",
    originalUrl:
      "https://lh4.googleusercontent.com/3dcsm3lnYFjJV-rg12VAC2BBRfdOqlxf5L4LwLhQS-FxTAUdOIQetTpcus6n2trklN6QnEvkkE0x3WwQ22x9UR4qUaYqcKGtNVhwmb1_oGXY5R_Jt-iLtaIDjAP_LrtHow=w740",
  },
  {
    id: 45,
    title: "Pretty Lake",
    trueLabel: "ai",
    imagePath: "/art/44.jpg",
    width: 740,
    height: 465,
    attribution: "This is AI art by Jack Galler.",
    attributionUrl: "https://x.com/gallerdude",
    originalUrl:
      "https://lh6.googleusercontent.com/FFKq4pHeGbgjhudm24RpEI2m6kWr3MT7i-j3is3s4Z6bv84CEcsoh8reRp8fNZvaFTGZOZe5Vw_QFyPdnJSHs0UzswR0XrtXrO7l3xCF27pPxPdDjMSLfU-Glz1GbYJOuQ=w740",
  },
  {
    id: 46,
    title: "Landing Craft",
    trueLabel: "ai",
    imagePath: "/art/45.png",
    width: 740,
    height: 456,
    attribution: "This is AI art by Ryan Wise.",
    commentary:
      "Ryan gave me lots of good sci-fi AI images, and I chose this one. People got it pretty easily, and I keep second-guessing myself and wondering if some of the others were better.",
    originalUrl:
      "https://lh3.googleusercontent.com/p1k3v214SBIFd-YAFUc1LE-rk0RJhC-pdPQl20bXzIoaAJym-7gi0zOLxgYyTH9s7soIE-xzgPZ_NNr0ovN21qkA8gGBwEg4cPQK7eRz6mRJMsxCIjOFgwM_V5HKxLkqWw=w740",
  },
  {
    id: 47,
    title: "Flailing Limbs",
    trueLabel: "human",
    imagePath: "/art/46.png",
    width: 495,
    height: 787,
    attribution:
      "This is “Replacement Parts” by Kara Walker, who is considered among The 25 Best Collage Artists In The World.",
    attributionUrl:
      "https://www.contemporaryartissue.com/top-25-collage-artists-in-the-world-a-complete-survey/",
    originalUrl:
      "https://lh4.googleusercontent.com/076HFMSMmKdZWQVS5jnrhUjWltVm7LZjqfwI8LByDi5vgJsOVbmpEpPdroZ-4zUuJqkfBiWtjuI-z797zQaqVgpXBgqNEg8w-SAEwo4JG7OFsb_pdj-ZBdLv8gPjbb7s4g=w495",
  },
  {
    id: 48,
    title: "Colorful Town",
    trueLabel: "human",
    imagePath: "/art/47.png",
    width: 740,
    height: 482,
    attribution: "This is “Entrance To The Village Of Osny” by Paul Gauguin, 1882.",
    attributionUrl: "https://collections.mfa.org/objects/33274",
    originalUrl:
      "https://lh5.googleusercontent.com/9Fi7KNamAP6Bpnl6ydWYiU0gqQrVdHrePJQpMxdLRpqLgJ6xjJoaM_xVUVyVHYhmMoLii9bP47A7Z2xKUNGW819VnHQf8NHEQHizfCMMi9bRaKJ_StO8UKzQNIysix-QpQ=w740",
  },
  {
    id: 49,
    title: "Mediterranean Town",
    trueLabel: "ai",
    imagePath: "/art/48.jpg",
    width: 740,
    height: 1004,
    attribution: "This is AI art by Jack Galler.",
    attributionUrl: "https://x.com/gallerdude",
    originalUrl:
      "https://lh3.googleusercontent.com/jK8zTfOthxzDWV5J3DkV7Do99PjbyUjVhYDWANtsKmnBKNaiEaD947URJXn5ie40HeFnTcI3VI481rZywCCrPX8rn_5teDnhFhTtIPoBaONpUGQFJdT_ti0pSYo8N7B13w=w740",
  },
  {
    id: 50,
    title: "Punk Robot",
    trueLabel: "ai",
    imagePath: "/art/49.png",
    width: 740,
    height: 509,
    attribution: "This is AI art by Ryan Wise.",
    originalUrl:
      "https://lh5.googleusercontent.com/G1-rLNozTq0xJPxDhalHIWcKT9DNLgVFj5q64y975AKXVAEm_6Q5IdVOc8lHSPZpXeBib-lc9JolIt52TS2vFJqTVdYN7weH5edZLPR_890EgYGY341JOqAbzA-YBnCoyQ=w740",
  },
]
